# Generated by Django 5.2.3 on 2025-06-17 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
